### ISSUE TITLE
Implement A* algorithm

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/maze-runner#3]
Correct the already implemented A* algorithm in algorithms/Astar.js so that it works properly.

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #3 

Step for completing the task:

1. Fork the repo
2. Make you necessary changes to the file
3. Submit a PR

**Comment by Dasblanquett98** [comment]
May I Take this? Thanks :)

**Comment by priyanshbalyan** [comment]
Sure. Go right ahead!

**Comment by Guddu327** [comment]
Hey, I am new to open source and I see that already someone is working on this issue. Can I take this issue as well just to learn more about it?

**Comment by priyanshbalyan** [comment]
@Guddu327 You can, yeah.

**Comment by priyanshbalyan** [comment]
@Dasblanquett98 Are you still on it?

**Comment by Guddu327** [comment]
Thank you. I went through the repo and forked it. I see that you have mentioned that algorithm is already implemented and it needs to be corrected. Could you please elaborate on the issue that I have to fix...

**Comment by priyanshbalyan** [comment]
@Guddu327 Uncomment the code in components/buttonbar.jsx and then run the project and click on visualise A* button. You will find that the visualisation is not finding the path between two nodes and is running in a different direction than intended. You need to correct it so the algorithm successfully finds the path between two nodes similar as other already implemented algorithms.

**Comment by Guddu327** [comment]
I user `npm run build` to build the project modules and then `npm start` to start the project. I can see multiple buttons on the start page but none of them are responding. For example, if I am clicking `Generate Maze`, nothing is coming up on the page. Could you please guide me through starting the project (if an alternate way exists)...?

**Comment by priyanshbalyan** [comment]
@Guddu327 Run it with ``npm run dev``

**Comment by priyanshbalyan** [comment]
@Guddu327 Hey! are you still on it?

**Comment by ervsam** [comment]
Hi! I am new to open source projects but have experience in path finding algorithms. Is it fine if I use this issue as practice?

**Comment by priyanshbalyan** [comment]
@ervsam Yep you can.

**Comment by rmotmans** [comment]
Hi! fairly new to open source project and github. Could i also take this?

**Comment by priyanshbalyan** [comment]
@rmotmans sure

**Comment by rmotmans** [comment]
What is the problem exactly? When I try it local everything seems fine.

**Comment by priyanshbalyan** [comment]
@rmotmans Open components/buttonbar.jsx. Uncomment the commented out code. Now run the project with npm run dev. You will find the Visualise A* button and when you click it it doesn't seem to function. The issue is for fixing this.

**Comment by rmotmans** [comment]
@priyanshbalyan I did that. A* button seems to work for me. The algorithm starts and finds the shortest path.

**Comment by priyanshbalyan** [comment]
@rmotmans Take a look at this video to understand how the A* algorithm should work https://www.youtube.com/watch?v=g024lzsknDo
