### ISSUE TITLE
Style buttons

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/maze-runner#4]
Style the buttons using basic CSS or you can use a UI framework like Material UI.
You can also add basic animations to the buttons.

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #4 

Step for completing the task:
1. Fork the repo
2. Make you necessary changes in components/buttonbar.jsx
3. Submit a PR

Leave a star if you like the project!

**Comment by Reego** [comment]
Hey, can I take this one? Appreciate it.

**Comment by priyanshbalyan** [comment]
@Reego Sure go right ahead!

**Comment by aliN500** [comment]
@priyanshbalyan Done.
